"""Remove organization_id from users table

Revision ID: 700f76b02d1a
Revises: e4969c8c1bf6
Create Date: 2025-03-21 17:42:58.706493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '700f76b02d1a'
down_revision: Union[str, None] = 'e4969c8c1bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samplermodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_samplermodes_id'), 'samplermodes', ['id'], unique=False)
    op.create_table('samplertypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_samplertypes_id'), 'samplertypes', ['id'], unique=False)
    op.create_table('sdmodels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdmodels_id'), 'sdmodels', ['id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.Enum('TRIAL', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('max_api_calls_per_month', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('typecontrols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_index(op.f('ix_typecontrols_id'), 'typecontrols', ['id'], unique=False)
    op.create_table('controlmodels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('typecontrol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['typecontrol_id'], ['typecontrols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_controlmodels_id'), 'controlmodels', ['id'], unique=False)
    op.create_table('controlmodules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('typecontrol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['typecontrol_id'], ['typecontrols.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_controlmodules_id'), 'controlmodules', ['id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('preview_url', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('sdmodel_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('negative_prompt', sa.String(), nullable=True),
    sa.Column('resize_mode', sa.Enum('JUSTRESIZE', 'CROPANDRESIZE', 'RESIZEANDFILL', name='resizemode'), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('save_images', sa.Boolean(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('cfg_scale', sa.Integer(), nullable=False),
    sa.Column('sampler_mode_id', sa.Integer(), nullable=False),
    sa.Column('sampler_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sampler_mode_id'], ['samplermodes.id'], ),
    sa.ForeignKeyConstraint(['sampler_type_id'], ['samplertypes.id'], ),
    sa.ForeignKeyConstraint(['sdmodel_id'], ['sdmodels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_id'), 'models', ['id'], unique=False)
    op.create_table('sdmodel_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_name', sa.String(), nullable=False),
    sa.Column('sdmodel_id', sa.Integer(), nullable=False),
    sa.Column('typecontrol_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sdmodel_id'], ['sdmodels.id'], ),
    sa.ForeignKeyConstraint(['typecontrol_id'], ['typecontrols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdmodel_versions_id'), 'sdmodel_versions', ['id'], unique=False)
    op.create_table('controlnet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('control_model_id', sa.Integer(), nullable=False),
    sa.Column('control_module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('guidance_start', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('guidance_end', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('weight', sa.NUMERIC(precision=4, scale=2), nullable=False),
    sa.Column('control_mode', sa.Enum('BALANCED', 'MYPROMTISMOREIMPORTANT', 'CONTROLNETISMOREIMPORTANT', name='controlmode'), nullable=True),
    sa.Column('resize_mode', sa.Enum('JUSTRESIZE', 'CROPANDRESIZE', 'RESIZEANDFILL', name='controlresizemode'), nullable=True),
    sa.ForeignKeyConstraint(['control_model_id'], ['controlmodels.id'], ),
    sa.ForeignKeyConstraint(['control_module_id'], ['controlmodules.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['sdmodels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_controlnet_id'), 'controlnet', ['id'], unique=False)
    op.create_table('subscription_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('payment_method_id', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_controlnet_association',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('controlnet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['controlnet_id'], ['controlnet.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'controlnet_id')
    )
    op.create_table('verification_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('BUSINESS_LICENSE', 'TAX_ID', 'IDENTITY_PROOF', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verification_notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['organization_members.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_participants',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('participant_name', sa.String(length=255), nullable=False),
    sa.Column('participant_email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_statistics',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('images_generated', sa.Integer(), nullable=True),
    sa.Column('storage_used_bytes', sa.Integer(), nullable=True),
    sa.Column('api_calls', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.Column('generated_url', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('image_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_rate_limits_key', table_name='rate_limits')
    op.drop_index('idx_rate_limits_window', table_name='rate_limits')
    op.drop_table('rate_limits')
    op.drop_index('idx_sessions_expiry', table_name='sessions')
    op.drop_index('idx_sessions_refresh', table_name='sessions')
    op.drop_index('idx_sessions_token', table_name='sessions')
    op.drop_index('idx_sessions_user', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_table('users')
    op.add_column('admins', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('admins', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('admins', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('admins', sa.Column('role', sa.Enum('ADMIN', 'ORGANIZATION', 'USER', name='userrole'), nullable=False))
    op.add_column('admins', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('admins', sa.Column('firebase_uid', sa.String(length=255), nullable=True))
    op.add_column('admins', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('admins_user_id_key', 'admins', type_='unique')
    op.drop_index('idx_admins_user_id', table_name='admins')
    op.create_unique_constraint(None, 'admins', ['email'])
    op.create_unique_constraint(None, 'admins', ['firebase_uid'])
    op.drop_constraint('admins_user_id_fkey', 'admins', type_='foreignkey')
    op.drop_column('admins', 'user_id')
    op.drop_column('admins', 'permissions')
    op.add_column('audit_logs', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('member_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.UUID(), nullable=True))
    op.alter_column('audit_logs', 'action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('audit_logs', 'details',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_category', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.drop_constraint('audit_logs_user_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'admins', ['admin_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'organization_members', ['member_id'], ['id'])
    op.drop_column('audit_logs', 'category')
    op.drop_column('audit_logs', 'user_id')
    op.add_column('organization_members', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('organization_members', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('organization_members', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('organization_members', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('organization_members', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('organization_members', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organization_members', sa.Column('firebase_uid', sa.String(length=255), nullable=True))
    op.alter_column('organization_members', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'ORGANIZATION', 'USER', name='userrole'),
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.drop_index('idx_org_members_org', table_name='organization_members')
    op.drop_index('idx_org_members_role', table_name='organization_members')
    op.drop_index('idx_org_members_user', table_name='organization_members')
    op.drop_constraint('organization_members_user_id_organization_id_key', 'organization_members', type_='unique')
    op.create_unique_constraint(None, 'organization_members', ['firebase_uid'])
    op.drop_constraint('organization_members_user_id_fkey', 'organization_members', type_='foreignkey')
    op.drop_column('organization_members', 'user_id')
    op.drop_column('organization_members', 'permissions')
    op.add_column('organizations', sa.Column('contact_email', sa.String(length=255), nullable=False))
    op.add_column('organizations', sa.Column('contact_phone', sa.String(length=50), nullable=True))
    op.add_column('organizations', sa.Column('verification_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('verification_notes', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('business_description', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('rejected_reason', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('subscription_tier', sa.Enum('TRIAL', 'BASIC', 'PRO', 'ENTERPRISE', name='subscriptiontier'), nullable=False))
    op.add_column('organizations', sa.Column('subscription_status', sa.Enum('ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=False))
    op.add_column('organizations', sa.Column('subscription_start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('subscription_end_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('max_users', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('max_storage_gb', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('max_api_calls_per_month', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('billing_email', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('billing_address', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('payment_method_id', sa.String(), nullable=True))
    op.alter_column('organizations', 'status',
               existing_type=postgresql.ENUM('pending', 'active', 'suspended', name='organization_status'),
               type_=sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='verificationstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::organization_status"))
    op.drop_index('idx_organizations_owner', table_name='organizations')
    op.drop_index('idx_organizations_status', table_name='organizations')
    op.drop_constraint('organizations_name_key', 'organizations', type_='unique')
    op.drop_constraint('organizations_owner_id_fkey', 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'owner_id')
    op.drop_column('organizations', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('organizations', sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('organizations_owner_id_fkey', 'organizations', 'users', ['owner_id'], ['id'])
    op.create_unique_constraint('organizations_name_key', 'organizations', ['name'])
    op.create_index('idx_organizations_status', 'organizations', ['status'], unique=False)
    op.create_index('idx_organizations_owner', 'organizations', ['owner_id'], unique=False)
    op.alter_column('organizations', 'status',
               existing_type=sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='verificationstatus'),
               type_=postgresql.ENUM('pending', 'active', 'suspended', name='organization_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::organization_status"))
    op.drop_column('organizations', 'payment_method_id')
    op.drop_column('organizations', 'billing_address')
    op.drop_column('organizations', 'billing_email')
    op.drop_column('organizations', 'max_api_calls_per_month')
    op.drop_column('organizations', 'max_storage_gb')
    op.drop_column('organizations', 'max_users')
    op.drop_column('organizations', 'subscription_end_date')
    op.drop_column('organizations', 'subscription_start_date')
    op.drop_column('organizations', 'subscription_status')
    op.drop_column('organizations', 'subscription_tier')
    op.drop_column('organizations', 'rejected_at')
    op.drop_column('organizations', 'rejected_reason')
    op.drop_column('organizations', 'business_description')
    op.drop_column('organizations', 'business_type')
    op.drop_column('organizations', 'verification_notes')
    op.drop_column('organizations', 'verification_submitted_at')
    op.drop_column('organizations', 'contact_phone')
    op.drop_column('organizations', 'contact_email')
    op.add_column('organization_members', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('organization_members', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('organization_members_user_id_fkey', 'organization_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'organization_members', type_='unique')
    op.create_unique_constraint('organization_members_user_id_organization_id_key', 'organization_members', ['user_id', 'organization_id'])
    op.create_index('idx_org_members_user', 'organization_members', ['user_id'], unique=False)
    op.create_index('idx_org_members_role', 'organization_members', ['role'], unique=False)
    op.create_index('idx_org_members_org', 'organization_members', ['organization_id'], unique=False)
    op.alter_column('organization_members', 'role',
               existing_type=sa.Enum('ADMIN', 'ORGANIZATION', 'USER', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'member'::character varying"))
    op.drop_column('organization_members', 'firebase_uid')
    op.drop_column('organization_members', 'last_login')
    op.drop_column('organization_members', 'status')
    op.drop_column('organization_members', 'last_name')
    op.drop_column('organization_members', 'first_name')
    op.drop_column('organization_members', 'password_hash')
    op.drop_column('organization_members', 'email')
    op.add_column('audit_logs', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_user_id_fkey', 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_category', 'audit_logs', ['category'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'user_agent',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'member_id')
    op.drop_column('audit_logs', 'admin_id')
    op.drop_column('audit_logs', 'organization_id')
    op.add_column('admins', sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('admins_user_id_fkey', 'admins', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'admins', type_='unique')
    op.drop_constraint(None, 'admins', type_='unique')
    op.create_index('idx_admins_user_id', 'admins', ['user_id'], unique=False)
    op.create_unique_constraint('admins_user_id_key', 'admins', ['user_id'])
    op.drop_column('admins', 'last_login')
    op.drop_column('admins', 'firebase_uid')
    op.drop_column('admins', 'status')
    op.drop_column('admins', 'role')
    op.drop_column('admins', 'last_name')
    op.drop_column('admins', 'first_name')
    op.drop_column('admins', 'password_hash')
    op.drop_column('admins', 'email')
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('super_admin', 'admin', 'member', 'user', name='user_role'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'active', 'suspended', 'banned', name='user_status'), server_default=sa.text("'pending'::user_status"), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('verification_token_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('failed_login_attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_failed_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='password_reset_tokens_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='password_reset_tokens_pkey'),
    sa.UniqueConstraint('token', name='password_reset_tokens_token_key'),
    comment='Password reset tokens for user password recovery'
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sessions_pkey'),
    sa.UniqueConstraint('refresh_token', name='sessions_refresh_token_key'),
    sa.UniqueConstraint('token', name='sessions_token_key')
    )
    op.create_index('idx_sessions_user', 'sessions', ['user_id'], unique=False)
    op.create_index('idx_sessions_token', 'sessions', ['token'], unique=False)
    op.create_index('idx_sessions_refresh', 'sessions', ['refresh_token'], unique=False)
    op.create_index('idx_sessions_expiry', 'sessions', ['expires_at'], unique=False)
    op.create_table('rate_limits',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('window_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('last_attempt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='rate_limits_pkey'),
    sa.UniqueConstraint('key', name='rate_limits_key_key')
    )
    op.create_index('idx_rate_limits_window', 'rate_limits', ['window_start'], unique=False)
    op.create_index('idx_rate_limits_key', 'rate_limits', ['key'], unique=False)
    op.drop_table('images')
    op.drop_table('usage_statistics')
    op.drop_table('event_participants')
    op.drop_table('verification_documents')
    op.drop_table('model_controlnet_association')
    op.drop_table('events')
    op.drop_table('api_keys')
    op.drop_table('subscription_history')
    op.drop_index(op.f('ix_controlnet_id'), table_name='controlnet')
    op.drop_table('controlnet')
    op.drop_index(op.f('ix_sdmodel_versions_id'), table_name='sdmodel_versions')
    op.drop_table('sdmodel_versions')
    op.drop_index(op.f('ix_models_id'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_controlmodules_id'), table_name='controlmodules')
    op.drop_table('controlmodules')
    op.drop_index(op.f('ix_controlmodels_id'), table_name='controlmodels')
    op.drop_table('controlmodels')
    op.drop_index(op.f('ix_typecontrols_id'), table_name='typecontrols')
    op.drop_table('typecontrols')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_sdmodels_id'), table_name='sdmodels')
    op.drop_table('sdmodels')
    op.drop_index(op.f('ix_samplertypes_id'), table_name='samplertypes')
    op.drop_table('samplertypes')
    op.drop_index(op.f('ix_samplermodes_id'), table_name='samplermodes')
    op.drop_table('samplermodes')
    # ### end Alembic commands ###
